### ISSUE TITLE
Rise Roblox Bug

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#100]
**Describe the bug**
Rise turns into Roblox, seems to be a scaling issue? 

**To Reproduce**
1. Import Model

**Expected behavior**
The Rise Model is imported

**Files**
Included in Issue

[Uploading c0004_051_00.zip…]()

**Comment by MadMax1960** [comment]
Ok I actually seem to have found the issue, it's something related to the bind pose. When doing the "scaleless" option instead of the default one it imports big, but ok. If I go into rest mode its normal size, but the pose bind mode is huge.

**Comment by MadMax1960** [comment]
Ok github wont let me upload so https://cdn.discordapp.com/attachments/831687902824103977/1141097146746155038/c0004_051_00.zip

**Comment by Pherakki** [comment]
This appears to be due to inconsistent scales inside the file, which the "Scaleless Rest Pose" import option circumvents. I can't think of a way to detect this without placing a model into both the reconstructed bind pose and the scaleless rest pose on import and making sure each vertex is the same within some delta, so I will close this issue for now and make one for the future that will try to identify a way to detect if this kind of issue is present in the model.
