### ISSUE TITLE
GAP Animations won't load 

### ISSUE THREAD

**Issue by yahi-ko** [Pherakki/BlenderToolsForGFS#154]
**Describe the bug**
Versions 2.0 to 2.1 won't load any GAP Animations on 3.6 to 4.0 Blender
However, i was able to open a gap using the 0.1.1 ver on 3.6 Blender

**To Reproduce**
1. Open a model: ex. Character/0001/.gmd' 
2. Then load a gap animation: ex. Character/0001/Battle/BB0001_052.GAP
3. Select the model before importing the gap

**Expected behavior**
Loading gap animations 

**Files**
C0001_001_00.GMD
BB0001_052.GAP

**Additional context**
None

**Comment by Pherakki** [comment]
The GAP animation data is imported, but as of [v0.2](https://github.com/Pherakki/BlenderToolsForGFS/releases/tag/v0.2), there is now a UI for generating NLA tracks from the animation data instead of the animation data being automatically directly imported to the NLA editor.

You will find that GAP UI in the `GFS Model` panel on the properties panel for your `Armature` object. Please refer to the documentation if you need to locate that panel in the UI and have difficulty using it. You can access the documentation by any of the following means:
1. Navigating to the `docs` folder of the plugin release you have downloaded,
2. Going to the `Addon Properties` (the window where you enable/disable plugins, clicking the dropdown arrow on the `BlenderToolsForGFS` addon), and clicking the `Open Documentation` button,
3. Deactivating and re-activating the plugin, which will show you the welcome message for the plugin, which also has an `Open Documentation` button that will open your local copy of the docs. Note that this splash screen only works on Blender 3.0+.

Please re-open the issue if the documentation does not solve your problem.
