### ISSUE TITLE
GAP failing to export

### ISSUE THREAD

**Issue by WisteriaSp** [Pherakki/BlenderToolsForGFS#96]
**Describe the bug**
GAP failing to export for some reason.

**To Reproduce**
1. Open the attached .blend
2. Export the GAP
3. See error

**Expected behavior**
It should export

**Files**
https://drive.google.com/file/d/1M9PQL2iiGefSIPp6y9UW09Ny88p5Dduc/view?usp=sharing
[traceback.txt](https://github.com/Pherakki/BlenderToolsForGFS/files/12114661/traceback.txt)

**Additional context**
Animations 18, 33, and 34 are edited. The GAP saved fine the last time I exported it but now it's crashing for some reason. Traceback attached.

**Comment by WisteriaSp** [comment]
The issue seems to occur if certain keyframes like location do not contain every axis (X, Y, Z). This is what happened with the jacket bones in animation 18.

**Comment by Pherakki** [comment]
This is happening because the exporter cannot identify an available GFS keyframe structure that is valid for the data provided. The error message can definitely be cleaned up, and this part of the code is definitely the roughest part and can use some improvement.

You should be able to get a functional export for now by:
1. Ensuring that each bone has a position AND rotation AND a scale animation,
2. Ensuring each bone has a position AND rotation AND NOT a scale animation.

I would guess this is being triggered by some bones only having position or rotation animations, or having a combination of position + scale or rotation + scale.
I know that this is an annoying and weird restriction, but it looks like it's one thing that slipped through the net when getting the animation export ready (it was a tough bit to get working in a remotely user-friendly way).

The "fix" (for me to implement for the next release) will be to automatically create dummy animation data on export that fills the missing transforms, such as exporting unit rotations alongside the position animation data if not rotation track is provided, since the game has extremely rigid requirements for what animation data must exist.

**Comment by Pherakki** [comment]
Should be fixed by 279a6a7811ba26b6d4e884d1d7e9b6c06df7dd17
